### ISSUE TITLE
Double finger to draw?

### ISSUE THREAD

**Issue by hebbian** [yuppielabel/YPDrawSignatureView#21]
I have to put my two fingers in order to draw, is this the default behaviour?

**Comment by GJNilsen** [comment]
No, thats something I have never even heard of before, this is the first time someone had this issue. I would love to see how you have implemented the class, maybe you did something wrong, because this should not happen.

**Comment by hebbian** [comment]
Hi @GJNilsen , I figured it out.

It's because I'm using another lib [(LGSideMenuController)](https://github.com/Friend-LGA/LGSideMenuController) that swallow up all pan gesture from the current view controller.

Thanks for the awesome code.

@Friend-LGA

**Comment by GJNilsen** [comment]
Hi!  

Thats great news it was not the signature class. The code was only possible because of the great support from the community.  
Have a great day!

## 

Geert Jan Korsbø Nilsen
Sent with Airmail  

På 6. september 2016 på 05.15.15, hebbian (notifications@github.com(mailto:notifications@github.com)) skrev:

**Comment by GJNilsen** [comment]
Turned out it had mothing to do with the signature class.
