### ISSUE TITLE
Drawing process

### ISSUE THREAD

**Issue by sssbohdan** [yuppielabel/YPDrawSignatureView#37]
It seems that drawing process works incorrect(tiny tails in the end of lines) - [screenshot]( http://imgur.com/a/rzbPP). I may be wrong, but it seems that problem is caused by these lines of code:
```
override public func touchesEnded(_ touches: Set <UITouch>, with event: UIEvent?) {
        if self.controlPoint < 4 {
            let touchPoint = self.points[0]
            self.path.move(to: CGPoint(x: touchPoint.x-1.0,y: touchPoint.y))
            self.path.addLine(to: CGPoint(x: touchPoint.x+1.0,y: touchPoint.y))
            self.setNeedsDisplay()
        }
```

**Comment by GJNilsen** [comment]
Setting the end caps to round would remedy the problem. I guess that would be a better solution anyway, making the signature look more natural. Ideally the class should have variable line width responding on force, utilizing ForceTouch and/or Apple Pencil. The reason why variable line width has not been implemented, is because the drawing routines has to be completely rewritten...

Bug has now been fixed.
