### ISSUE TITLE
Resume Signature

### ISSUE THREAD

**Issue by AshotN** [yuppielabel/YPDrawSignatureView#44]
There is no way to set a signature in the signature view right now. Would be a nice feature

**Comment by GJNilsen** [comment]
Im not sure if I understand you correctly. Do you want to be able to display a stored signature or image? Like a placeholder? I would appreciate it if you could elaborate a tad.

**Comment by AshotN** [comment]
Sorry for the ambiguity, I meant it would be nice if we were able to display a signature in the signature view and allow the user to resume from it.

If someone starts a signature, accidentally leaves the view and comes back.

**Comment by GJNilsen** [comment]
At first glance, the feature sounds great. It would not be difficult to implement it, but Im having some objections to it.

In some countries, digital signatures like the one collected by this class, is equivalent with its analog counterpart. So if it should be legally binding, it has to be as close to the analog counterpart as possible, and even the process of signing should be close to it as well.
A signature is created by a flowing motion, a collection of curves, combined into a symbol. If one should draw one stroke, put the paper away, and later add another stroke, and repeating this process until the signature was complete, it would not have the natural flow in it. Using signature analyzing tools, the signature would have been flagged as a forgery. It would also be more easy to forge a signature as well if stroke by stroke was saved, because then one could step backwards if there was a too big deviation from the original signature. The legal aspect and validity of the signature is something Im focusing on.

To conclude, there will not be a function for do a partial signature, and finishing it later by loading it from a store.

**Comment by AshotN** [comment]
Alright, how about display the signature as read only. Saves a lot of time, rather then displaying the image version over the signature view. Also a user can still do it piece by piece, so I'm not sure about the legal issues. Thanks

**Comment by GJNilsen** [comment]
Well, someone always sign a document within a very short timeframe, so being able to sign partial signatures, and come back to continue the signature is not something a normal person would do. So after considering it, the idea sounds even worse now. Maybe there would be an edge use case for it, but as long as Im not aware of a real need for such a function, it will not be added.
