### ISSUE TITLE
error:required code signature missing

### ISSUE THREAD

**Issue by FahdSaif** [yuppielabel/YPDrawSignatureView#61]
![errorinib](https://user-images.githubusercontent.com/20011570/43057080-957fd1e2-8e72-11e8-860f-fed83502f3c2.png)

Hi Nielsen and development team, we are working with IOS SWIFT 3.2 and xcode version 9.2, MacOS Sierra, and getting the error in the attached png file. Failed to render, required code signature missing. The program does compile and I am able to get the signature also correctly, but this error coming during the design time is really bothering me. Are we missing something important or very basic here?. Kindly assist please.Anyone who may have encountered this?. Thanks in advance.

**Comment by GJNilsen** [comment]
This is because somebody made a Cocoapod of this class. Its something I have strongly advised against, you should just download the class, and then add it to your project i stead of as a framework. That shit does just not work.

The simple solution: Delete the Cocoapod, and remove any trace of the YPDrawSignatureView.framework. Then clone this repo, or even simpler, just download the single file that contains the class, add it to your project, and you are done. No import statements, no dependencies, no build scripts or other crap. Keep it simple.
