### ISSUE TITLE
performance issue when drawing 3 lines or more

### ISSUE THREAD

**Issue by X901** [yuppielabel/YPDrawSignatureView#72]
Hi ,
I notice that when drawing a lot of lines
the performance change very bad
you will notice lag when drawing!

I notice it very clear when drawing first line ok, 2nd line also ok
3rd and 4th line you notice it 

see this video

https://cl.ly/5222627d0eb2

you will notice how bad the performance became at the end!

**Comment by X901** [comment]
This another video
https://cl.ly/384a0c9f4f3a

What I notice the more you draw the more the performance become bad

**Comment by saormart** [comment]
@X901, well that looks like you're running in a simulator...
Do you have the same issue with a device ?
I'm using it in my application that I have two fields to sign, and it's working great with no problem!
I have tried the same thing you just did in your videos, and the only way to start having performance issues is if you "paint" the signature field....
So it's purpose is for signatures, not for "paint" or manually write a "book" lol !

**Comment by X901** [comment]
This also happened with Device 
You know when you do something  and Users surprising you ?
This what I faced , it should be for signing only, But the managers whose use the app they write some commends and also signing ! 
That how I know about this issue

**Comment by saormart** [comment]
All right! The device I've tested is an iPad mini that works well for signatures only (so far no complaints)!
Have you consider add a textbox for the managers "Notes" ?
I'm saying that because in our case we need the users to add a note on a textbox and sign ! Both fields are mandatory! May by add a textbox to write something would be easy for the users to type something and if they type something wrong, would be easy to correct than if you "draw" some notes and made a mistake you need to clear all and start over again!

**Comment by saormart** [comment]
But if you still want to use a signature field to add notes, you may test this other framework [here](https://github.com/ipraba/EPSignature) that may solve your problem!
I was using that one before, but I was trying to avoid add too many frameworks on my app, and YPDrawSignatureView was a better choice for me due it's works well in my app, and it's simple to implement / modify!

**Comment by GJNilsen** [comment]
@X901 I'm not seeing any performance issues on the iPhone X. What kind of device are you running it on?

https://cl.ly/be617aaa483d

I ran some instruments tests on it as well, and I see absolutely no decrease in performance when before the signature path control points exceed 1024. When hitting this high a number, you don't use it for a signature anymore, that's more like taking notes.

The reason for this decrease in performance is because the raw points are saved in memory. If one would save a bitmap instead, there would not be any performance issues. That's the price to pay for having the signature as a vector graphic.

So if one would use the class within the scope of its intended use, it will work as expected. For the time being this issue will be closed and is marked as Out of Scope. If it is a problem for more users, then I maybe implement some caching.

**Comment by X901** [comment]
@saormart there is a textview for note , but for unknown reason some users like to write it using Apple Pencil this was not expected before. so I think I need to look for draw framework not signature draw framework 

@GJNilsen I was using iPad Pro , Thank you for let me know about how it does work 
so I need to change the framework itself to another one

**Comment by GJNilsen** [comment]
@X901 There will be support for the Apple Pencil in version 2 of the class, and probably some caching there. Maybe that will get the job done for you. I dont know when the class will be done, it depends on how much I get to do on my spare time.
